- name: Put config from all Mikrotik RouterOS devices
  hosts: MT
  gather_facts: no
  debugger: on_failed

  tasks:
   
  - name: Check ping
    net_ping:
        dest: MT
    register: checkping
    when: checkping == 1 
        - name: Collect Address_list Before Config
                routeros_command:
                        commands: ip firewall address-list print terse where list="test_address-lists"

        register: IPFWADLISTBFR

        - name: Config new prefix to list "test_address-lists"
                routeros_command:
                        commands: 
                        - ip firewall address-list add address="{{ item }}" disabled=no list=test_address-lists
                        with_items:
                                - 1.1.1.2/32
                                - 1.1.1.3/32
                                - 1.1.1.4/32
                                - 1.1.1.5/32
                                - 1.1.1.6/32

        - name: Collect Address_list After Config
                routeros_command:
                        commands: ip firewall address-list print terse where list="test_address-lists"
                register: IPFWADLISTAFT

        - name: Export configuration commands
                routeros_command:
                        commands: export

                register: EXPORT

        - set_fact: time="{{lookup('pipe','date \"+%Y-%m-%d-%H-%M\"')}}"
        
        - name: save output to a file
                connection: local
                copy:
                        content="===Before Config===\n{{ IPFWADLISTBFR.stdout|join('\n') }}\n\n===After Config===\n{{ IPFWADLISTAFT.stdout|join('\n') }}\n"
                        dest="/etc/ansible/RouterOS_Log/{{ inventory_hostname }}_acl_cfg_{{ time }}.txt"
    
        - name: Send a success email
                 mail:
                        host: smtp-gw.totisp.net
                        port: 25 
                        from: s.chollathep <s.chollathep@totisp.net>
                        to: s.chollathep <s.chollathep@totisp.net>
                        subject: Installation Update
                        body: 'The installation is complete.'